
POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"jess"
}


####

GET  http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiamVzcyIsImlhdCI6MTY5NDUzNTk3MCwiZXhwIjoxNjk0NTM2MDIwfQ.wF-yb5qu1HfNplmrUbf4zedD_sGI1fiV4YGakEv5kGI


###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiamVzcyIsImlhdCI6MTY5NDUzNjAyNX0.V5oc7cXn1aL0YZlsAFmvfDfIwLBpv8q5GUY90JcvzVc"
}


###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiamVzcyIsImlhdCI6MTY3NDUzNDU0OH0.i7TrUVuUot1AY9rWmXsggtmrdElwjDQ0tc7zc37B0xQ"
}